### ISSUE TITLE
False negative reports on eframe, Inflector and opentelemetry crates

### ISSUE THREAD

**Issue by duncanawoods** [citreae535/sparse-crates#6]
I am getting some false errors on some crates. Feels like a caching error maybe?

- `eframe`, `egui_extras` : extension says latest version is 0.27.2 not 0.29.2
  - https://crates.io/crates/eframe
- `Inflector` : extension says crate not found in registry but afaik, it's there
  - https://crates.io/crates/Inflector
  - :exclamation: note: the capitalised crate name is unusual so could be an unrelated bug
- `opentelemetry` says latest stable is 0.16 not 0.26
  - https://crates.io/crates/opentelemetry

Linux, rustc 1.82.0.

``` toml
[package]
name = "example_crates"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui_extras = "0.29.1"
Inflector = "0.11.4"
opentelemetry = { version = "0.26.0", features = ["trace", "metrics"] }
opentelemetry_sdk = { version = "0.26.0", default-features = false, features = [
  "trace",
  "rt-tokio",
] }
opentelemetry-semantic-conventions = "0.26.0"
opentelemetry-otlp = { version = "0.26.0", features = ["metrics"] }
opentelemetry-stdout = { version = "0.26.0", features = ["trace", "metrics"] }
```

**Eframe**

![image](https://github.com/user-attachments/assets/b5813680-7ba8-47a7-a11b-168fc18f835d)

**Inflector**

![image](https://github.com/user-attachments/assets/cca9ab77-66fe-4d45-9ff5-8ca5af334d91)

**opentelemetry**

![image](https://github.com/user-attachments/assets/c88c5906-0b54-436e-a49a-b678ea1f09bb)
